select * from CHK.CHECK_NOTICE where CHECKEAPPLIETIME ='2016-07-01';

select n.NOTICEID,n.CREATEDATE,n.CHECKAPPLIEDTIME,r.checkRule as RULECONTEXT,r.ITEMNAME,t.TYPENAME,n.NODENAME,o.OBJNAME,n.ISPASS ,n.content FROM
		xnychk.CHECK_NOTICE n
		JOIN xnychk.CHECK_RULE_INFO r ON
		n.itemId=r.itemId left join  XNYCHK.CHECK_TYPE_INFO t on n.CHECKTYPEID=t.TYPEID left join XNY.OBJECT_INFO o on n.OBJID=o.OBJID
update CHK.DISPUTE_LOG set update_time =sysdate;
update CHK.DISPUTE_LOG_SUBMIT set update_time =sysdate;
update CHK.CHECK_COMPLAINT_LOG set update_time =sysdate;
update CHK.CHECK_COMPLAINT_LOG_TMP set update_time =sysdate;


select * from CHK.CHECK_DAY_MONTH    ;

delete from XNY.XNY_DAYBEFORE_OPERA_RATE;

DROP TABLE XNY.RECORDMANT_LOG restrict;
CREATE TABLE XNY.RECORDMANT_LOG(
LOGID VARCHAR2(50) NOT NULL,
APPLIEDTIME VARCHAR2(50) NOT NULL,
TYPEID NUMBER(38,0) NOT NULL,
ITEMID NUMBER(38,0) NOT NULL,
OBJNAME VARCHAR2(500) NOT NULL,
HandleTYPE VARCHAR2(50),
RECauses VARCHAR2(50),
REREMARKS VARCHAR2(5000),
PRONAME VARCHAR2(20),
PROSECTOR VARCHAR2(100),
PROTIME VARCHAR2(50),
CREATEUSER NUMBER(38,0) NOT NULL,
CREATETIME TIMESTAMP(6) DEFAULT NOW(),
UPDATEUSER VARCHAR2(100),
UPDATETIME VARCHAR2(50),
RELTIME VARCHAR2(50),
RESTATUS INT,
REMARKS VARCHAR2(5000),
REFILENAME VARCHAR2(500),
REFILEPATH VARCHAR2(1000),
NOT CLUSTER PRIMARY KEY("LOGID")) STORAGE(ON MAIN, CLUSTERBTR);
COMMENT ON TABLE XNY.RECORDMANT_LOG IS '操作运维记录';
COMMENT ON COLUMN XNY.RECORDMANT_LOG.LOGID IS '主键';
COMMENT ON COLUMN XNY.RECORDMANT_LOG.APPLIEDTIME IS '考核月份';
COMMENT ON COLUMN XNY.RECORDMANT_LOG.TYPEID IS '考核分型';
COMMENT ON COLUMN XNY.RECORDMANT_LOG.ITEMID IS '考核子项';
COMMENT ON COLUMN XNY.RECORDMANT_LOG.OBJNAME IS '处理电厂';
COMMENT ON COLUMN XNY.RECORDMANT_LOG.HandleTYPE IS '处理类型';
COMMENT ON COLUMN XNY.RECORDMANT_LOG.RECauses IS '修改原因';
COMMENT ON COLUMN XNY.RECORDMANT_LOG.REREMARKS IS '修改内容';
COMMENT ON COLUMN XNY.RECORDMANT_LOG.PRONAME IS '提出人';
COMMENT ON COLUMN XNY.RECORDMANT_LOG.PROSECTOR IS '提出部门';
COMMENT ON COLUMN XNY.RECORDMANT_LOG.PROTIME IS '提出时间';
COMMENT ON COLUMN XNY.RECORDMANT_LOG.CREATEUSER IS '创建用户';
COMMENT ON COLUMN XNY.RECORDMANT_LOG.CREATETIME IS '创建时间';
COMMENT ON COLUMN XNY.RECORDMANT_LOG.UPDATEUSER IS '修改人';
COMMENT ON COLUMN XNY.RECORDMANT_LOG.UPDATETIME IS '修改时间';
COMMENT ON COLUMN XNY.RECORDMANT_LOG.RELTIME IS '发布时间';
COMMENT ON COLUMN XNY.RECORDMANT_LOG.RESTATUS IS '状态';
COMMENT ON COLUMN XNY.RECORDMANT_LOG.REMARKS IS '备注说明';
COMMENT ON COLUMN XNY.RECORDMANT_LOG.REFILENAME IS '附件名称';
COMMENT ON COLUMN XNY.RECORDMANT_LOG.REFILEPATH IS '附件路径';

update XNY.RECORDMANT_LOG set RESTATUS=0;

update CHK.CHECK_DAY_MONTH set state=0;
update CHK.CHECK_DAY_MONTH set state=1 where checkmonth=07;










