 select  distinct tmr.MAPID,t.MPOINTID from (
 select t2.OBJNAME,t1.STATIONID,t1.MPOINTID,t1.UNITTYPECODE from OBJ.PLAN_UNIT_INFO t1 join obj.object_info t2 on t1.PLANUNITID=t2.objid where t1.UNITTYPECODE in (1,2)
 ) t join TMR.OBJECT_MAPPING tmr on t.MPOINTID=tmr.objid where t.MPOINTID=29735100;
 

select * from CHK.MPOINT_ENERGY_1MON WHERE APPLIEDTIME ='2017-11-01'

select * from TMR.MPOINT_ENERGY_1MIN WHERE APPLIEDTIME >='2017-10-01'
   SELECT * FROM XNYCHK.CHECK_NOTICE cn      LEFT JOIN XNY.object_info oi on cn.OBJID = oi.OBJID
   LEFT JOIN XNYCHK.check_rule_info ri      on cn.ITEMID = ri.ITEMID 
   LEFT JOIN XNYCHK.check_type_info ti on cn.CHECKTYPEID = ti.TYPEID      where  cn.CHECKAPPLIEDTIME ='2017-11-01'
   
DELETE from XNYCHK.CHECK_NOTICE_TMP WHERE CHECKAPPLIEDTIME='2017-11-01'
   
select OBJID, OBJNAME,OBJCLASS from XNY.OBJECT_INFO  where isavailable = 1 and objname  like '%拉马%' OBJCLASS in(40,160,1,90) 



select * from YWXT.XRH_ONE_FREQUENCY_PARAMETER where dc_ID=1444  

select * FROM YWXT.XRH_DC_BASE_PARAMS_AUDIT where BUSINESS_TYPE=10014 order by ID desc

 SELECT A.DC_ID AS A_DC_ID,A.FDCDDMC,A.FDCLX,B.OBJ_VALUE,B.OBJ_ID AS   B_OBJ_ID,
 C.*,   (case when D.IS_AUDIT is null then -1 else D.IS_AUDIT   end) as IS_AUDIT,
 "YWXT"."getdname"('STSKJMS',C.SDDSKZMS) as   SDDSKZMSVALUE,"YWXT"."getdname"('HTSKJMS',C.SDDSKZLX) as SDDSKZLXVALUE   ,
 "YWXT"."getdname"('RMJZXSZD',C.SDRMJZXS) as   SDRMJZXSVALUE,"YWXT"."getdname"('YCTPGNSFTR',C.YCTPGNTR) as YCTPGNTRVALUE,
 "YWXT"."getdname"('SDXFFS',C.SDXFFS) as SDXFFSVALUE,   (case when XT.IS_AUDIT is null then -1 else XT.IS_AUDIT   end) as XTIS_AUDIT,
 D.AUDIT_INFO AS AUDIT_INFO,XT.AUDIT_INFO AS XAUDIT_INFO   
 FROM YWXT.XRH_DC AS A   
 INNER JOIN YWXT.XRH_BASE_OBJ AS B   ON   A.DC_ID=B.DC_ID   AND   B.METE_CODE='MUD_SB_GENERATINGUNIT'  AND A.FDCLX   IN   ('sdc','hdc')   
 LEFT JOIN   YWXT.XRH_ONE_FREQUENCY_PARAMETER AS C ON   A.DC_ID=C.DC_ID AND   B.OBJ_ID =C.OBJ_ID AND C.STATUS_N_O =1   
LEFT JOIN   YWXT.XRH_DC_BASE_PARAMS_AUDIT D ON C.ID=D.BUSINESS_KEY AND   D.BUSINESS_TYPE=10014   
LEFT JOIN   YWXT.XRH_DC_BASE_PARAMS_AUDIT_XTYX XT ON C.ID=XT.BUSINESS_KEY AND   XT.BUSINESS_TYPE=10014        
where                         A.DC_ID =1444                     and           A.DDJG = '省调'         
                              ORDER BY A.FDCDDMC,B.OBJ_VALUE  
                              
 select T2.MAPID,T2.OBJID from XNY.STATION_INFO t1 join  TMR.OBJECT_MAPPING t2 on t1.MPOINTID=t2.OBJID ;
 select T1.DPLANID,T2.MPOINTID from XNY.MAP_STATION_INFO T1 LEFT JOIN XNY.STATION_INFO T2 ON T1.STATIONID=T2.STATIONID  where T1.DPLANID!='' and T1.DPLANID is not null;
                              
  